/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: MW.begin.proto */

#ifndef PROTOBUF_C_MW_2ebegin_2eproto__INCLUDED
#define PROTOBUF_C_MW_2ebegin_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Mw__Begin Mw__Begin;


/* --- enums --- */


/* --- messages --- */

/*
 * Respond to whole supersteps begin.
 * message type: 1
 */
struct  _Mw__Begin
{
  ProtobufCMessage base;
  /*
   **< master id 
   */
  int32_t s_id;
  /*
   **< worker id 
   */
  int32_t d_id;
  /*
   **< 0: OK to begin, 1: need to wait 
   */
  int32_t state;
};
#define MW__BEGIN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mw__begin__descriptor) \
    , 0, 0, 0 }


/* Mw__Begin methods */
void   mw__begin__init
                     (Mw__Begin         *message);
size_t mw__begin__get_packed_size
                     (const Mw__Begin   *message);
size_t mw__begin__pack
                     (const Mw__Begin   *message,
                      uint8_t             *out);
size_t mw__begin__pack_to_buffer
                     (const Mw__Begin   *message,
                      ProtobufCBuffer     *buffer);
Mw__Begin *
       mw__begin__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mw__begin__free_unpacked
                     (Mw__Begin *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Mw__Begin_Closure)
                 (const Mw__Begin *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mw__begin__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_MW_2ebegin_2eproto__INCLUDED */
