/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: MW.end.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "MW.end.pb-c.h"
void   mw__end__init
                     (Mw__End         *message)
{
  static Mw__End init_value = MW__END__INIT;
  *message = init_value;
}
size_t mw__end__get_packed_size
                     (const Mw__End *message)
{
  assert(message->base.descriptor == &mw__end__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mw__end__pack
                     (const Mw__End *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mw__end__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mw__end__pack_to_buffer
                     (const Mw__End *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mw__end__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mw__End *
       mw__end__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mw__End *)
     protobuf_c_message_unpack (&mw__end__descriptor,
                                allocator, len, data);
}
void   mw__end__free_unpacked
                     (Mw__End *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mw__end__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mw__end__field_descriptors[3] =
{
  {
    "s_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Mw__End, s_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Mw__End, d_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Mw__End, state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mw__end__field_indices_by_name[] = {
  1,   /* field[1] = d_id */
  0,   /* field[0] = s_id */
  2,   /* field[2] = state */
};
static const ProtobufCIntRange mw__end__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mw__end__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mw.end",
  "End",
  "Mw__End",
  "mw",
  sizeof(Mw__End),
  3,
  mw__end__field_descriptors,
  mw__end__field_indices_by_name,
  1,  mw__end__number_ranges,
  (ProtobufCMessageInit) mw__end__init,
  NULL,NULL,NULL    /* reserved[123] */
};
