/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: MW.end.proto */

#ifndef PROTOBUF_C_MW_2eend_2eproto__INCLUDED
#define PROTOBUF_C_MW_2eend_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Mw__End Mw__End;


/* --- enums --- */


/* --- messages --- */

/*
 * Notify workers to end supersteps.
 * message type: 4
 */
struct  _Mw__End
{
  ProtobufCMessage base;
  /*
   **< master id 
   */
  int32_t s_id;
  /*
   **< worker id 
   */
  int32_t d_id;
  /*
   **< 0: OK to end, 1: need to go on 
   */
  int32_t state;
};
#define MW__END__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mw__end__descriptor) \
    , 0, 0, 0 }


/* Mw__End methods */
void   mw__end__init
                     (Mw__End         *message);
size_t mw__end__get_packed_size
                     (const Mw__End   *message);
size_t mw__end__pack
                     (const Mw__End   *message,
                      uint8_t             *out);
size_t mw__end__pack_to_buffer
                     (const Mw__End   *message,
                      ProtobufCBuffer     *buffer);
Mw__End *
       mw__end__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mw__end__free_unpacked
                     (Mw__End *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Mw__End_Closure)
                 (const Mw__End *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mw__end__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_MW_2eend_2eproto__INCLUDED */
