/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: MW.nextss_start.proto */

#ifndef PROTOBUF_C_MW_2enextss_5fstart_2eproto__INCLUDED
#define PROTOBUF_C_MW_2enextss_5fstart_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Mw__NextssStart Mw__NextssStart;


/* --- enums --- */


/* --- messages --- */

/*
 **
 * Next superstep starts.
 * Master sends this message to all workers before next superstep starts.
 * message type: 3
 */
struct  _Mw__NextssStart
{
  ProtobufCMessage base;
  /*
   **< master id 
   */
  int32_t s_id;
  /*
   **< worker id 
   */
  int32_t d_id;
  /*
   **< next superstep number 
   */
  int32_t superstep;
  /*
   **< count of node messages the worker should receive before next superstep 
   */
  int64_t node_msg;
  /*
   **< global aggregator value before next superstep 
   */
  size_t n_aggr_global;
  ProtobufCBinaryData *aggr_global;
};
#define MW__NEXTSS_START__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mw__nextss_start__descriptor) \
    , 0, 0, 0, 0, 0,NULL }


/* Mw__NextssStart methods */
void   mw__nextss_start__init
                     (Mw__NextssStart         *message);
size_t mw__nextss_start__get_packed_size
                     (const Mw__NextssStart   *message);
size_t mw__nextss_start__pack
                     (const Mw__NextssStart   *message,
                      uint8_t             *out);
size_t mw__nextss_start__pack_to_buffer
                     (const Mw__NextssStart   *message,
                      ProtobufCBuffer     *buffer);
Mw__NextssStart *
       mw__nextss_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mw__nextss_start__free_unpacked
                     (Mw__NextssStart *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Mw__NextssStart_Closure)
                 (const Mw__NextssStart *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mw__nextss_start__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_MW_2enextss_5fstart_2eproto__INCLUDED */
