/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: WM.curss_finish.proto */

#ifndef PROTOBUF_C_WM_2ecurss_5ffinish_2eproto__INCLUDED
#define PROTOBUF_C_WM_2ecurss_5ffinish_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Wm__CurssFinish Wm__CurssFinish;


/* --- enums --- */


/* --- messages --- */

/*
 **
 * Current superstep finishes.
 * Worker sends this message to master after current superstep computing finishes.
 * message type: 2
 */
struct  _Wm__CurssFinish
{
  ProtobufCMessage base;
  /*
   **< worker id 
   */
  int32_t s_id;
  /*
   **< master id 
   */
  int32_t d_id;
  /*
   **< current superstep number 
   */
  int32_t superstep;
  /*
   **< count of computations in current superstep 
   */
  int64_t compute;
  /*
   **< count of messages received in current superstep 
   */
  int64_t recv_msg;
  /*
   **< count of messages sent in current superstep 
   */
  int64_t sent_msg;
  /*
   **< count of messages for each worker in current superstep 
   */
  size_t n_worker_msg;
  int64_t *worker_msg;
  /*
   **< count of active vertices left after current superstep 
   */
  int64_t act_vertex;
  /*
   **< local aggregator value after current superstep 
   */
  size_t n_aggr_local;
  ProtobufCBinaryData *aggr_local;
};
#define WM__CURSS_FINISH__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&wm__curss_finish__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0,NULL, 0, 0,NULL }


/* Wm__CurssFinish methods */
void   wm__curss_finish__init
                     (Wm__CurssFinish         *message);
size_t wm__curss_finish__get_packed_size
                     (const Wm__CurssFinish   *message);
size_t wm__curss_finish__pack
                     (const Wm__CurssFinish   *message,
                      uint8_t             *out);
size_t wm__curss_finish__pack_to_buffer
                     (const Wm__CurssFinish   *message,
                      ProtobufCBuffer     *buffer);
Wm__CurssFinish *
       wm__curss_finish__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   wm__curss_finish__free_unpacked
                     (Wm__CurssFinish *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Wm__CurssFinish_Closure)
                 (const Wm__CurssFinish *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor wm__curss_finish__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_WM_2ecurss_5ffinish_2eproto__INCLUDED */
