/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: WM.end.proto */

#ifndef PROTOBUF_C_WM_2eend_2eproto__INCLUDED
#define PROTOBUF_C_WM_2eend_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Wm__End Wm__End;


/* --- enums --- */


/* --- messages --- */

/*
 * Report to master after ending supersteps.
 * message type: 5
 */
struct  _Wm__End
{
  ProtobufCMessage base;
  /*
   **< worker id 
   */
  int32_t s_id;
  /*
   **< master id 
   */
  int32_t d_id;
  /*
   **< 0: end sucessfully, 1: end unsuccessfully 
   */
  int32_t state;
};
#define WM__END__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&wm__end__descriptor) \
    , 0, 0, 0 }


/* Wm__End methods */
void   wm__end__init
                     (Wm__End         *message);
size_t wm__end__get_packed_size
                     (const Wm__End   *message);
size_t wm__end__pack
                     (const Wm__End   *message,
                      uint8_t             *out);
size_t wm__end__pack_to_buffer
                     (const Wm__End   *message,
                      ProtobufCBuffer     *buffer);
Wm__End *
       wm__end__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   wm__end__free_unpacked
                     (Wm__End *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Wm__End_Closure)
                 (const Wm__End *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor wm__end__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_WM_2eend_2eproto__INCLUDED */
