/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: WW.nodemsg_list.proto */

#ifndef PROTOBUF_C_WW_2enodemsg_5flist_2eproto__INCLUDED
#define PROTOBUF_C_WW_2enodemsg_5flist_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Ww__NodemsgList Ww__NodemsgList;


/* --- enums --- */


/* --- messages --- */

/*
 **
 * Node2Node message list.
 * Worker may send a series of this message to dest-worker during a superstep.
 * If num_msgs is 0, this is a signal which means the worker have finished
 * sending node2node messages to dest-worker in current superstep.
 * message type: 6
 */
struct  _Ww__NodemsgList
{
  ProtobufCMessage base;
  /*
   **< source worker id 
   */
  int32_t s_id;
  /*
   **< destination worker id 
   */
  int32_t d_id;
  /*
   **< current superstep number 
   */
  int32_t superstep;
  /*
   **< number of node messages on the list 
   */
  int32_t num_msgs;
  /*
   **< size of one piece of node message 
   */
  int32_t msg_size;
  /*
   **< content of compressed node messages 
   */
  ProtobufCBinaryData msgs;
};
#define WW__NODEMSG_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ww__nodemsg_list__descriptor) \
    , 0, 0, 0, 0, 0, {0,NULL} }


/* Ww__NodemsgList methods */
void   ww__nodemsg_list__init
                     (Ww__NodemsgList         *message);
size_t ww__nodemsg_list__get_packed_size
                     (const Ww__NodemsgList   *message);
size_t ww__nodemsg_list__pack
                     (const Ww__NodemsgList   *message,
                      uint8_t             *out);
size_t ww__nodemsg_list__pack_to_buffer
                     (const Ww__NodemsgList   *message,
                      ProtobufCBuffer     *buffer);
Ww__NodemsgList *
       ww__nodemsg_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ww__nodemsg_list__free_unpacked
                     (Ww__NodemsgList *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Ww__NodemsgList_Closure)
                 (const Ww__NodemsgList *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ww__nodemsg_list__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_WW_2enodemsg_5flist_2eproto__INCLUDED */
